/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./__root"

// Create Virtual Routes

const ContactLazyImport = createFileRoute("/contact")()
const IndexLazyImport = createFileRoute("/")()

// Create/Update Routes

const ContactLazyRoute = ContactLazyImport.update({
  path: "/contact",
  getParentRoute: () => rootRoute,
}).lazy(() => import("./contact.lazy").then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
}).lazy(() => import("./index.lazy").then((d) => d.Route))

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ContactLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/contact"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/contact": {
      "filePath": "contact.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
